"""Changed status to is_done in Todo table

Revision ID: 73825e075ee1
Revises: 54e4f31b7ee4
Create Date: 2021-07-20 11:06:57.051057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73825e075ee1'
down_revision = '54e4f31b7ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todoes', sa.Column('is_done', sa.Boolean(), nullable=True))
    op.drop_column('todoes', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todoes', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('todoes', 'is_done')
    # ### end Alembic commands ###
